### ISSUE TITLE
Slide Formats

### ISSUE THREAD

**Issue by adamleerich** [chiefmurph/CASRBootcamp17#4]
Hello...

Brian, I absolutely love your logo, but I don't really want it at the bottom of my slides.  So, I have moved the _output.yaml file to an _archive folder and made sure that all of your .Rmd files have everything needed in the header.  

Is it OK with everyone if our slides are in different formats?

**Comment by PirateGrunt** [comment]
I'm cool with slides in different formats.

I'm going to take another look at my slides this evening and do a final knit tomorrow (Sunday) morning. Adam, moving the output.yaml means that everyone has to have appropriate YAML in their files. I'll do a check of that in the morning. 

I'll wait a bit for Dan to chime in, but otherwise will close this issue as I do the final knit tomorrow.

**Comment by chiefmurph** [comment]
I don't know what slides you are looking at, but that's ok. I don't know how Brian's logo got on Adam's slides, but I would prefer they not get on mine if possible.

**Comment by PirateGrunt** [comment]
The logo gets in via some custom .css. I'll do a final check to make sure that it isn't on anyone's slides other than mine.

Going to go ahead and close this issue as I think we're all ok.

**Comment by adamleerich** [comment]
Yep, sounds good to me.
